### ISSUE TITLE
Incorrect behavior when Data Layer array name is changed.

### ISSUE THREAD

**Issue by bennet-roy** [adobe/adobe-client-data-layer#90] opened 2020-06-08 20:11 UTC
### Expected Behaviour

When we change the default Data Layer array name, any data/function added to the the changed array before the library is loaded must be processed after the library is loaded.

### Actual Behaviour

As of now, if we add any data/function to the changed Data Layer array before the library is loaded, it is not processed at all.

#### Steps to Reproduce

Load https://hello-roy.herokuapp.com/#/

It has the following the source code

```html
    <script>
    window.adobeDataLayer = window.adobeDataLayer || [];
    window.adobeDataLayer.push(function(dl) {
        window.myDataLayer = dl;
    });
    </script>
<script type="text/javascript" src="/js/acdl.js" async defer></script>
  <script>
    window.myDataLayer = window.myDataLayer || [];
    window.myDataLayer.push({
        "page": {
            "title": "Getting Started"
        }
    });

    window.adobeDataLayer = window.adobeDataLayer || [];
    window.adobeDataLayer.push({
        "category": {
            "title": "Overview"
        }
    });

</script>
```

On the console, type myDataLayer.getState()

You should see `category.title` attribute in the DL, but `page.title` is missing. This means that any changes to myDataLayer array is not processed at all.

**Comment by gabrielwalt** [comment] 2020-06-09 08:10
Independently of the data layer, your script cannot work: when doing `window.myDataLayer = dl;`, you indeed create a new reference to the data layer, but you also overwrite the reference to the array that you started to fill already. What you should do instead at that place is to push everything that existed in the prior array back into the new reference of the data layer:

```javascript
<script>
    window.adobeDataLayer = window.adobeDataLayer || [];
    window.adobeDataLayer.push(function(dl) {
        var priorMyDataLayer = window.myDataLayer;
        window.myDataLayer = dl;
        for (var i = 0, length = window.myDataLayer.length; i < length; i++) {
            window.myDataLayer.push(priorMyDataLayer[i]);
        }
    });
</script>
```

However, while this might fix the problem temporarily, **I'd not recommend this**, because there might be other side effects to this approach, especially in edge-cases with function callbacks…

Instead, you should wait for issue #42 to be completed. Closing this issue here as it's not a bug of the data layer, and as we already have an issue for the desired improvement.

**Closed by gabrielwalt** 2020-06-09 08:10 UTC

**Comment by bennet-roy** [comment] 2020-06-11 21:44
Thanks @gabrielwalt . Can you please update the the wiki page with your example for renaming the Data Layer. I did not put enough thought when I copy pasted the current renaming example script from the wiki.

**Comment by gabrielwalt** [comment] 2020-06-11 21:50
Good point, I've removed that comment.
